name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [bash, pwsh, bash]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: pwsh
          - os: macos-latest
            shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libopencv-dev libx11-dev

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake opencv xquartz

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y cmake opencv
          # Handle X11 dependency if possible

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
        shell: ${{ matrix.shell }}
